export const TURN_SPEED = 450; // turn speed in degrees per second
export const SHIP_MAX_HEALTH = 100; // Maximum health points for ship
export const SHIP_ASTEROID_DAMAGE = 25; // Damage from asteroid collision
export const SHIP_BOT_DAMAGE = 15; // Damage from bot collision
export const SHIP_HEALTH_REGEN_RATE = 1; // Health regeneration per second when not taking damage
export const SHIP_HEALTH_REGEN_DELAY = 5; // Seconds to wait before health regeneration starts
export const SHIP_THRUST = 5; // Thrust in pixels per second per second (Acceleration)
export const SHIP_SIZE = 30; // ship height in pixels
export const SHIP_EXPLODE_DUR = 0.3; // Ship explode time in seconds
export const SHIP_INV_DUR = 3; // Length of time ship is invulnerable in seconds
export const SHIP_INV_BLINK_DUR = 0.1; // Time between blinks when ship is invulnerable (seconds)
