import { beforeEach, describe, expect, it } from 'vitest';
import { GAME } from '../../../../src/constants';
import { Player } from '../../../../src/entities/player/Player';
import { MockPlayerInput } from '../../../../src/input/MockPlayerInput';
import { entityFactory } from '../../../../src/entities/EntityFactory';
import { Ship } from '../../../../src/entities/ship/Ship';
import {
  calculateHealthRegenDelayFrames,
  calculateHealthRegenPerFrame,
  shouldStartHealthRegeneration,
} from '../../../../src/entities/ship/shipUtils';

describe('Health Regeneration', () => {
  let ship: Ship;
  let botShip: Ship;

  beforeEach(() => {
    // Create a regular ship
    ship = new Ship({
      position: { x: 400, y: 300 },
      isBot: false,
    });

    // Create a bot ship
    botShip = new Ship({
      position: { x: 400, y: 300 },
      isBot: true,
    });
  });

  describe('Health Regeneration Calculations', () => {
    it('should calculate correct health regen per frame', () => {
      const regenPerFrame = calculateHealthRegenPerFrame();
      // At 60 FPS, 1 health per second = 1/60 = 0.0167 per frame
      expect(regenPerFrame).toBe(1 / 60);
      expect(regenPerFrame).toBeCloseTo(0.0167, 4);
    });

    it('should calculate correct health regen delay frames', () => {
      const delayFrames = calculateHealthRegenDelayFrames();
      // 5 seconds * 60 FPS = 300 frames
      expect(delayFrames).toBe(300);
    });

    it('should determine when health regeneration should start', () => {
      // Should start when lastDamageTime <= 0 and health < maxHealth
      expect(shouldStartHealthRegeneration(0, 50, 100)).toBe(true);
      expect(shouldStartHealthRegeneration(0, 100, 100)).toBe(false); // Already at max
      expect(shouldStartHealthRegeneration(0, 0, 100)).toBe(false); // Dead — server respawns
      expect(shouldStartHealthRegeneration(10, 50, 100)).toBe(false); // Still in damage cooldown
      expect(shouldStartHealthRegeneration(-1, 50, 100)).toBe(true); // Past cooldown
    });
  });

  describe('Health Regeneration Debug', () => {
    it('should debug the health regeneration issue', () => {
      ship.takeDamage(50); // Reduce health to 50
      const healthAfterDamage = ship.health;
      const initialLastDamageTime = ship.lastDamageTime;
      const initialHealthRegenTimer = ship.healthRegenTimer;

      // Verify initial state
      expect(healthAfterDamage).toBe(50);
      expect(initialLastDamageTime).toBe(60); // Should be GAME.FPS
      expect(initialHealthRegenTimer).toBe(300); // Should be 5 seconds * 60 FPS

      // Update health frame by frame to see what's happening
      for (let frame = 0; frame < 10; frame++) {
        const healthBefore = ship.health;
        ship.updateHealth();
        const healthAfter = ship.health;

        // Health should not decrease during damage cooldown
        expect(healthAfter).toBeGreaterThanOrEqual(healthBefore);
      }

      // Fast-forward to when regeneration should start (after 60 frames for lastDamageTime)
      for (let frame = 10; frame < 70; frame++) {
        ship.updateHealth();
      }

      // At this point, lastDamageTime should be 0 and regeneration should start
      expect(ship.lastDamageTime).toBe(0);

      // Continue updating to wait for healthRegenTimer to expire (additional 300 frames)
      const healthBeforeRegen = ship.health;
      for (let frame = 70; frame < 370; frame++) {
        ship.updateHealth();
      }

      // Health should have increased by now (after 360 total frames)
      expect(ship.health).toBeGreaterThan(healthBeforeRegen);
    });
  });

  describe('Ship Health Regeneration', () => {
    it('should not regenerate health when exploding', () => {
      ship.explode();
      const initialHealth = ship.health;

      ship.updateHealth();

      expect(ship.health).toBe(initialHealth);
    });

    it('should not regenerate health during damage cooldown', () => {
      ship.takeDamage(20);
      const healthAfterDamage = ship.health;

      // Update health multiple times during cooldown
      for (let i = 0; i < 10; i++) {
        ship.updateHealth();
      }

      expect(ship.health).toBe(healthAfterDamage);
    });

    it('should regenerate health after damage cooldown expires', () => {
      ship.takeDamage(20);
      const healthAfterDamage = ship.health;

      // Fast-forward past the damage cooldown (60 frames for lastDamageTime + 300 frames for healthRegenTimer)
      for (let i = 0; i < 360; i++) {
        ship.updateHealth();
      }

      // Health should have regenerated by at least 1
      expect(ship.health).toBeGreaterThan(healthAfterDamage);
    });
  });

  describe('Bot Ship Health Regeneration', () => {
    it('should regenerate health for bot ships', () => {
      botShip.takeDamage(30);
      const healthAfterDamage = botShip.health;

      // Fast-forward past damage cooldown
      for (let i = 0; i < 360; i++) {
        botShip.updateHealth();
      }

      // Health should have regenerated
      expect(botShip.health).toBeGreaterThan(healthAfterDamage);
    });

    it('should reproduce the bot health regeneration cap bug', () => {
      // Simulate the scenario: bot takes damage and health goes to 80
      botShip.takeDamage(20);
      const initialHealth = botShip.health;
      expect(initialHealth).toBe(80);

      // Verify timers are set correctly after damage
      expect(botShip.lastDamageTime).toBe(60); // GAME.FPS
      expect(botShip.healthRegenTimer).toBe(300); // 5 seconds * 60 FPS
      expect(botShip.isBot).toBe(true);

      // Fast-forward past the damage cooldown (60 frames for lastDamageTime + 300 frames for healthRegenTimer)
      for (let i = 0; i < 360; i++) {
        botShip.updateHealth();
      }

      // The health should have increased beyond 80
      expect(botShip.health).toBeGreaterThan(80);

      // Continue regenerating until max health to ensure it works fully
      const maxAdditionalFrames = 2000; // Should be plenty to reach max from 81
      let additionalFrames = 0;

      while (botShip.health < botShip.maxHealth && additionalFrames < maxAdditionalFrames) {
        botShip.updateHealth();
        additionalFrames++;
      }

      // Final check - should reach max health
      expect(botShip.health).toBe(botShip.maxHealth);
    });

    it('should verify bot health regeneration does not get stuck at 81', () => {
      // Simulate the exact reported issue: bot health stuck at 81
      botShip.takeDamage(20);
      expect(botShip.health).toBe(80);

      // Fast-forward to start regeneration
      for (let i = 0; i < 360; i++) {
        botShip.updateHealth();
      }

      // Should have started regenerating
      expect(botShip.health).toBeGreaterThan(80);

      // Now test the specific issue: simulate server sending health=81 when client has 80
      // This should be accepted as small regeneration
      const clientHealthBefore = botShip.health;
      expect(clientHealthBefore).toBeGreaterThanOrEqual(80);

      // Simulate server update with health = client health + 1 (small regeneration)
      const serverHealthUpdate = clientHealthBefore + 1;
      const mockState = {
        position: botShip.position,
        velocity: botShip.velocity,
        angle: botShip.angle,
        exploding: false,
        lives: 3,
        health: serverHealthUpdate,
        maxHealth: 100,
        lasers: undefined,
      };

      // Simulate the logic from BotSyncManager.updateRemoteBotState
      const isDamage = mockState.health < clientHealthBefore;
      const isFullHealth = mockState.health === botShip.maxHealth;
      const isSmallRegeneration =
        mockState.health > clientHealthBefore &&
        mockState.health <= clientHealthBefore + 2 &&
        mockState.health < botShip.maxHealth;

      // This should be accepted as small regeneration
      expect(isSmallRegeneration).toBe(true);

      // Update should be accepted
      if (isDamage || isFullHealth || isSmallRegeneration) {
        botShip.health = mockState.health;
      }

      expect(botShip.health).toBe(serverHealthUpdate);

      // Continue regeneration to ensure it doesn't get stuck
      const healthBeforeContinuedRegen = botShip.health;
      for (let i = 0; i < 100; i++) {
        botShip.updateHealth();
      }

      // Health should continue increasing
      expect(botShip.health).toBeGreaterThan(healthBeforeContinuedRegen);
    });
  });

  describe('Player Health Regeneration', () => {
    it('should regenerate health for player ships', () => {
      const player = new Player({
        id: 'test-player',
        name: 'Test Player',
        type: 'local',
        input: new MockPlayerInput(),
      });

      // Damage the player's ship
      player.ship.takeDamage(25);
      const healthAfterDamage = player.ship.health;

      // Fast-forward past damage cooldown
      for (let i = 0; i < 360; i++) {
        player.ship.updateHealth();
      }

      // Health should have regenerated
      expect(player.ship.health).toBeGreaterThan(healthAfterDamage);
    });

    it('should regenerate health for bot players', () => {
      const botPlayer = new Player({
        id: 'bot-player',
        name: 'Bot Player',
        type: 'bot',
        input: new MockPlayerInput(),
      });

      // Damage the bot's ship
      botPlayer.ship.takeDamage(30);
      const healthAfterDamage = botPlayer.ship.health;

      // Fast-forward past damage cooldown
      for (let i = 0; i < 360; i++) {
        botPlayer.ship.updateHealth();
      }

      // Health should have regenerated
      expect(botPlayer.ship.health).toBeGreaterThan(healthAfterDamage);
    });
  });

  describe('BotSyncManager Health Update Logic', () => {
    let botPlayer: Player;

    beforeEach(() => {
      // Create a bot player
      botPlayer = entityFactory.createBotPlayer('Test Bot');
    });

    it('should accept server health updates that represent damage', () => {
      // Set bot to full health initially
      botPlayer.ship.health = 100;

      // Simulate server sending lower health (damage)
      const serverState = {
        position: botPlayer.ship.position,
        velocity: botPlayer.ship.velocity,
        angle: botPlayer.ship.angle,
        exploding: false,
        lives: botPlayer.lives,
        health: 80, // Server says health is 80 (damage occurred)
        maxHealth: 100,
        lasers: undefined,
      };

      // Before the fix, this would have been ignored because 80 < 100 (server health lower)
      // After the fix, this should be accepted as damage
      const currentHealth = botPlayer.ship.health;
      expect(serverState.health).toBeLessThan(currentHealth); // 80 < 100 = true (damage)

      // Simulate the logic from updateRemoteBotState
      if (serverState.health < currentHealth || serverState.health === botPlayer.ship.maxHealth) {
        botPlayer.ship.health = serverState.health;

        if (serverState.health < currentHealth) {
          botPlayer.ship.lastDamageTime = GAME.FPS;
          botPlayer.ship.healthRegenTimer = calculateHealthRegenDelayFrames();
        }
      }

      // Health should be updated to 80
      expect(botPlayer.ship.health).toBe(80);
      // Timers should be reset for regeneration
      expect(botPlayer.ship.lastDamageTime).toBe(GAME.FPS);
      expect(botPlayer.ship.healthRegenTimer).toBe(calculateHealthRegenDelayFrames());
    });

    it('should reject server health updates that represent regeneration', () => {
      // Set bot to damaged health initially
      botPlayer.ship.health = 80;

      // Simulate server sending higher health (regeneration)
      const serverState = {
        position: botPlayer.ship.position,
        velocity: botPlayer.ship.velocity,
        angle: botPlayer.ship.angle,
        exploding: false,
        lives: botPlayer.lives,
        health: 85, // Server says health is 85 (regenerated)
        maxHealth: 100,
        lasers: undefined,
      };

      // Before the fix, this would have been accepted because 85 > 80 (server health higher)
      // After the fix, this should be rejected to let local regeneration continue
      const currentHealth = botPlayer.ship.health;
      expect(serverState.health).toBeGreaterThan(currentHealth); // 85 > 80 = true (regeneration)

      // Simulate the logic from updateRemoteBotState
      if (serverState.health < currentHealth || serverState.health === botPlayer.ship.maxHealth) {
        // This condition should be false for regeneration updates
        expect(serverState.health < currentHealth).toBe(false);
        expect(serverState.health === botPlayer.ship.maxHealth).toBe(false);

        // Health should NOT be updated
        expect(botPlayer.ship.health).toBe(80); // Should remain 80
      } else {
        // This branch should be taken for regeneration updates (server health > current health)
        // Health should remain unchanged to let local regeneration continue
        expect(botPlayer.ship.health).toBe(80);
      }
    });

    it('should accept server health updates when bot reaches max health', () => {
      // Set bot to nearly full health
      botPlayer.ship.health = 99;

      // Simulate server sending max health (regeneration completed)
      const serverState = {
        position: botPlayer.ship.position,
        velocity: botPlayer.ship.velocity,
        angle: botPlayer.ship.angle,
        exploding: false,
        lives: botPlayer.lives,
        health: 100, // Server says health is 100 (max health)
        maxHealth: 100,
        lasers: undefined,
      };

      const currentHealth = botPlayer.ship.health;
      expect(serverState.health).toBe(botPlayer.ship.maxHealth); // 100 === 100 = true

      // Simulate the logic from updateRemoteBotState
      if (serverState.health < currentHealth || serverState.health === botPlayer.ship.maxHealth) {
        botPlayer.ship.health = serverState.health;
      }

      // Health should be updated to 100
      expect(botPlayer.ship.health).toBe(100);
    });
  });

  describe('Health Regeneration Edge Cases', () => {
    it('should handle very small health increments correctly', () => {
      const regenPerFrame = calculateHealthRegenPerFrame();
      expect(regenPerFrame).toBeLessThan(1);

      // Test that small increments accumulate correctly
      let totalHealth = 0;
      for (let i = 0; i < 60; i++) {
        totalHealth += regenPerFrame;
      }

      // After 60 frames (1 second), should have 1 health
      expect(totalHealth).toBeCloseTo(1, 4);
    });

    it('should regenerate health continuously until max health', () => {
      ship.takeDamage(50); // Reduce health to 50
      const healthAfterDamage = ship.health;

      // Fast-forward past damage cooldown (60 frames for lastDamageTime + 300 frames for healthRegenTimer)
      for (let i = 0; i < 360; i++) {
        ship.updateHealth();
      }

      // Continue updating for a reasonable number of frames to see regeneration
      let updateCount = 0;
      const maxUpdates = 1000;
      while (ship.health < ship.maxHealth && updateCount < maxUpdates) {
        const healthBefore = ship.health;
        ship.updateHealth();
        const healthAfter = ship.health;

        // Health should either stay the same or increase
        expect(healthAfter).toBeGreaterThanOrEqual(healthBefore);

        updateCount++;
      }

      // Health should have increased significantly (at least 10 points)
      expect(ship.health).toBeGreaterThan(healthAfterDamage + 10);

      // If we didn't reach max health, that's fine - regeneration is slow by design
      // The important thing is that it's working and health is increasing
    });

    it('should not exceed max health during regeneration', () => {
      ship.takeDamage(10); // Reduce health to 90

      // Fast-forward past damage cooldown
      for (let i = 0; i < 360; i++) {
        ship.updateHealth();
      }

      // Continue updating many times
      for (let i = 0; i < 1000; i++) {
        ship.updateHealth();
      }

      // Should never exceed max health
      expect(ship.health).toBeLessThanOrEqual(ship.maxHealth);
    });

    it('should handle multiple damage events correctly', () => {
      ship.takeDamage(20);

      // Update health a few times
      for (let i = 0; i < 10; i++) {
        ship.updateHealth();
      }

      // Take more damage (should reset cooldown)
      ship.takeDamage(15);
      const healthAfterSecondDamage = ship.health;

      // Health should not have regenerated yet
      expect(ship.health).toBe(healthAfterSecondDamage);

      // Fast-forward past new cooldown
      for (let i = 0; i < 360; i++) {
        ship.updateHealth();
      }

      // Now health should regenerate
      expect(ship.health).toBeGreaterThan(healthAfterSecondDamage);
    });
  });
});
