#!/usr/bin/env bash
set -e

# Skip if running in CI environment
if [ -n "$CI" ]; then
  echo "Skipping Husky hooks in CI environment"
  exit 0
fi

echo "Ensuring staged files are linted/formatted..."
npx lint-staged

echo "Running TypeScript type check..."
npm run check:ts

echo "Running unit tests..."
npm run test

exit 0
