name: 'GeoAsteroidsTest'

on:
  push:
  pull_request:
    branches: ['main']
  schedule:
    - cron: '0 3 * * 0-6'

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: ['javascript', 'typescript']

    steps:
      - uses: actions/checkout@v3

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: ${{ matrix.language }}

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint with eslint
        run: npm run lint

      - name: Run coverage
        run: npm run coverage

      - name: Coveralls
        uses: coverallsapp/github-action@v2
